version: "2"         # required to adjust maintainability checks
plugins:
  csslint:
    enabled: true
  eslint:
    enabled: true
exclude_patterns:
  - "GPS_viewer/htdocs/leaflet.js"
  - "GPS_viewer/htdocs/ccchart-min.js"
