version: '2'
services:
    web:
        container_name: webui
        build:
            context: ./container/webui/compose

        environment:
            - STOCKER_CONF=/var/www/stocker/conf
            - PERL5LIB=/var/www/stocker/lib
        volumes:
            - ./:/var/www/stocker/repo:z
            - ./container/log/nginx:/var/log/nginx/web:z
            - ./dist/data:/var/www/stocker/data:z
        ports:
            - "8080:80"
