version: '2'
services:
    web:
        container_name: webui
        build:
            context: ./container/webui/compose

        volumes:
            - ./:/var/www/stocker/repo:z
            - ./container/log/nginx:/var/log/nginx/web:z
        ports:
            - "8080:80"
